### ISSUE TITLE
AXFlurryEventRecordStatus cannot be resolved to a type

### ISSUE THREAD

**Issue by udirub** [diwu/AnalyticX#19]
I just downloaded the newest version and I started getting this error in AnalyticXBridge.java.
This error is also present when I load the supplied example project.
I tried to find the AXFlurryEventRecordStatus in the code but I could only find it for C++ in the header file.
Where is the AXFlurryEventRecordStatus definition for Java?

**Comment by jmgomezg** [comment]
Hi, I'm getting the same issue, any news?

**Comment by haxpor** [comment]
@udirub Those types introduced in Flurry, and I'm the one who added it in iOS. I don't think Android code catches up with it. Someone might contribute to Android for this.

**Comment by diwu** [comment]
If anyone could fix this issue, please submit a pull request. Many thanks.

**Comment by jmgomezg** [comment]
On the C++ side we have a typedef defined on the AnaliticX.h

typedef enum {
    AXFlurryEventFailed = 0,
    AXFlurryEventRecorded,
    AXFlurryEventUniqueCountExceeded,
    AXFlurryEventParamsCountExceeded,
    AXFlurryEventLogCountExceeded,
    AXFlurryEventLoggingDelayed
} AXFlurryEventRecordStatus;

But I'm not sure what to do on the Java side, I tried to recreate the typedef but the returns funcions are falling to cast.

**Comment by jmgomezg** [comment]
If it helps, I managed to get the AnalyticXBridge.java file to compile, I downloaded latest Flurry Android SDK, replace the FlurryAgen.jar with the FlurryAnalytics-6.2.0.jar (or whatever version is), on the AnalyticXBridge.java rename AXFlurryEventRecordStatus to FlurryEventRecordStatus, and be sure we import all package:
import com.flurry.android.*;

But then I get a run time error:
JNI DETECTED ERROR IN APPLICATION: the return type of CallStaticIntMethodV does not match void com.diwublog.AnalyticX.AnalyticXBridge.Bridge(java.lang.String, java.lang.String, java.lang.String)'

Will keep you guys updated with my progress.

**Comment by jmgomezg** [comment]
I have pushed some changes to make this work on Android.

**Comment by diwu** [comment]
Hi all, if @jmgomezg 's pull request has fixed the issue, please let me know and I'll close the issue.

**Comment by haxpor** [comment]
I have no android dev environment with me right now, so if you guys think it's cool, please go ahead :) :+1:

**Comment by jmgomezg** [comment]
Sorry let me do some more checks, now I'm not 100% sure yet it's logging the events properly. I will confirm.

**Comment by jmgomezg** [comment]
Ok all working, Flurry was just taking a while to log the events. All good now, I have an android app working nicely with Android.

**Comment by diwu** [comment]
Cool I'll close it for now. Let me know if the issue persists.
